name: nbseq-min
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pip:
    - altair==5.1.2
    - mnemonicode==1.4.5
    - "git+https://github.com/caseygrun/nbseq.git#egg=nbseq"
  - altair-transform=0.2.0
  - anndata=0.9.2
  - biom-format=2.1.15
  - biopython=1.81
  - connectorx=0.3.1
  - dna_features_viewer=3.1.2
  - dnachisel=3.2.11
  - humanize=4.7.0
  - ipykernel=6.25.1
  - ipywidgets=8.1.0
  - logomaker=0.8
  - matplotlib=3.7.2
  - natsort=8.4.0
  - numpy=1.24.4
  - openpyxl=3.1.2
  - pandas=2.0.3
  - panel=1.2.1
  - pigz=2.6
  - plotly=5.16.0
  - plotnine=0.12.2
  - pysam=0.21.0
  - pyyaml=6.0
  - scikit-bio=0.5.9
  - scipy=1.10.0
  - seaborn=0.12.2
  - sqlalchemy
  - sqlite
