name: nbseq2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - altair-transform=0.2.0
  - anndata=0.9.2
  - bioconductor-biomformat=1.28.0
  - bioconductor-dada2=1.28.0
  - bioconvert=1.1.1
  - biom-format=2.1.15
  - biopython=1.81
  - connectorx=0.3.1
  - dna_features_viewer=3.1.2
  - dnachisel=3.2.11
  - humanize=4.7.0
  - ipykernel=6.25.1
  - ipywidgets=8.1.0
  - jupyter-server-proxy=4.0.0
  - logomaker=0.8
  - matplotlib=3.7.2
  - natsort=8.4.0
  - numba=0.57.1
  - numpy=1.24.4
  - openpyxl=3.1.2
  - pandas=2.0.3
  - panel=1.2.1
  - pigz=2.6
  - pip:
      - altair==5.1.0.dev0
      - mnemonicode=1.4.5
  - plotly=5.16.0
  - plotnine=0.12.2
  - pv=1.6.6
  - pysam=0.21.0
  - python-kaleido=0.2.1
  - pyyaml=6.0
  - r=4.3
  - r-cowplot=1.1.1
  - r-ggpmisc=0.5.3
  - r-ggpointdensity=0.1.0
  - r-ggrepel=0.9.3
  - r-ggstatsplot=0.12.0
  - r-ggtext=0.1.2
  - r-irkernel=1.3.2
  - r-plotly=4.10.2
  - r-reticulate=1.31
  - r-rmarkdown=2.24
  - r-tidymodels=1.1.0
  - r-tidyverse=2.0.0
  - r-vegan=2.6_4
  - rpy2=3.5.11
  - scikit-bio=0.5.9
  - scikit-learn=1.3.0
  - scipy=1.10.0
  - seaborn=0.12.2
  - siuba=0.4.2
  - statsmodels=0.14.0
  - sqlalchemy=2.0.19
  - sqlite=3.42.0
  - svgutils=0.3.4